class LocalizationData {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tl': {
      'app_title': 'Santo Rosaryo',
      'today_mystery': 'Misteryo ngayong araw',
      'interactive_title': 'Interaktibong Rosaryo',
      'interactive_subtitle': 'Gabay sa bawat butil ng rosaryo na may kasamang audio at canvas.',
      'guide_title': 'Gabay sa Pagbasa',
      'guide_subtitle': 'Buong teksto ng pagdarasal mula sa simula hanggang wakas.',
      'repeat_x': 'ULITIN NANG X',
      'step': 'Hakbang',
      'of': 'ng',
      'reading': 'Nagbabasa...',
      'meditation': 'PAGNINILAY-NILAY',
      'next_our_father': 'SUSUNOD: AMA NAMIN',
      'restart': 'Simula',
      'back': 'Bago',
      'stop': 'Tigilan',
      'auto': 'Auto',
      'dialog_close': 'Isara',
      'dialog_again': 'Muli',
      'dialog_title': 'Natapos ang Rosaryo!',
      'dialog_body': 'Salamat sa inyong debosyon.\nPanatag nawa ang inyong kalooban.',
      'intention_dialog_title': 'Intensyon sa Panalangin',
      'intention_dialog_desc': 'Bago simulan ang buong Rosaryo, maaari mong ialay ang panalanging ito para sa iyong pangkalahatang intensyon.',
      'intention_input_hint': 'Halimbawa: Iniaalay ko po ang Banal na Rosaryo na ito para sa kagalingan ng aking pamilya, para sa kapayapaan ng mundo, at para sa patnubay sa aking pag-aaral/trabaho...',
      'pray_without_intention': 'Magdasal nang Walang Intensyon',
      'start_with_intention': 'Ialay at Simulan',
      'general_intention_title': 'Pangkalahatang Intensyon',
      'quick_chip_family': 'Kagalingan ng Pamilya',
      'quick_chip_peace': 'Kapayapaan ng Mundo',
      'quick_chip_guidance': 'Patnubay sa Pag-aaral / Trabaho',
      'guide_intention_section_title': 'BAGO SIMULAN ANG BUONG ROSARYO (GENERAL INTENTIONS)',
      'guide_intention_note': 'Ito ang pinakakaraniwang ginagawa. Bago ka mag-antanda ng krus o bago dasalin ang Sumasampalataya, maaari mong ialay ang buong Rosaryo para sa iyong pangkalahatang intensyon.',
      'guide_intention_example_label': 'HALIMBAWA NA PANALANGIN NG INTENSYON:',
      'edit_intention': 'Isulat / Baguhin ang Intensyon',
    },
    'en': {
      'app_title': 'Holy Rosary',
      'today_mystery': 'Today\'s Mystery',
      'interactive_title': 'Interactive Rosary',
      'interactive_subtitle': 'Guided bead-by-bead rosary with audio and canvas.',
      'guide_title': 'Reading Guide',
      'guide_subtitle': 'Full text of prayers from beginning to end.',
      'repeat_x': 'REPEAT X',
      'step': 'Step',
      'of': 'of',
      'reading': 'Reading...',
      'meditation': 'MEDITATION',
      'next_our_father': 'NEXT: OUR FATHER',
      'restart': 'Restart',
      'back': 'Back',
      'stop': 'Stop',
      'auto': 'Auto',
      'dialog_close': 'Close',
      'dialog_again': 'Again',
      'dialog_title': 'Rosary Completed!',
      'dialog_body': 'Thank you for your devotion.\nMay peace be with you.',
      'intention_dialog_title': 'Prayer Intentions',
      'intention_dialog_desc': 'Before starting the Holy Rosary, you may offer this prayer for your general intentions.',
      'intention_input_hint': 'Example: I offer this Holy Rosary for the healing of my family, peace in the world, and guidance in my studies/work...',
      'pray_without_intention': 'Pray without Intention',
      'start_with_intention': 'Offer & Start',
      'general_intention_title': 'General Intentions',
      'quick_chip_family': 'Healing of Family',
      'quick_chip_peace': 'World Peace',
      'quick_chip_guidance': 'Guidance in Studies / Work',
      'guide_intention_section_title': 'BEFORE STARTING THE ROSARY (GENERAL INTENTIONS)',
      'guide_intention_note': 'This is most commonly done. Before making the Sign of the Cross or praying the Creed, you may offer the entire Rosary for your general intention.',
      'guide_intention_example_label': 'SAMPLE PRAYER OF INTENTION:',
      'edit_intention': 'Write / Edit Intention',
    },
  };

  static String getText(String lang, String key) {
    return _localizedValues[lang]?[key] ?? key;
  }
}
